<a href="https://colab.research.google.com/github/woomook0524/google_colab/blob/main/Numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#모듈과 패키지


In [ ]:
#모듈은 변수, 함수, 클래스를 담고 있는 파일 (.py)
#패키지는 여러 모듈을 묶은것 (폴더)
#import 모듈

#모듈.변수
#모듈.함수()
# 모듈.클래스()

In [ ]:
import math
print(math.pi)

3.141592653589793


In [ ]:
from math import pi,sqrt
print(pi)
print(sqrt(4))

3.141592653589793
2.0


In [ ]:
from math import sqrt as s, pi as p
print(p)
print(s(4))

3.141592653589793
2.0


In [ ]:
import numpy as np # numpy는 라이브러리 (패키지와 모듈들을 모아놓음)다 numerical python
a= np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
import numpy.random
print(numpy.random.randn(3,3)) # Normal distribution, (3,3)은 3행 3열 짜리를 의미

[[-0.21354683 -0.8870367  -1.63713481]
 [-0.58117167 -1.90097373  0.6636987 ]
 [ 1.23727438  0.49264038 -0.73356269]]


In [ ]:
from numpy.random import *
print(rand(3,3)) # uniform distribution

[[0.39018106 0.37646169 0.34606031]
 [0.99605025 0.03688627 0.76846296]
 [0.28778607 0.84637879 0.868391  ]]


In [ ]:
from numpy.random import randn as rn, rand as r
print(rn(3,3))
print(r(3,3))

[[-1.6257684  -1.0049925  -1.30518409]
 [ 1.14227154 -0.12152202 -2.03627761]
 [ 1.18561368  1.27023749  0.28691293]]
[[0.48113271 0.95503362 0.43208295]
 [0.22937865 0.06267845 0.93736422]
 [0.41195143 0.93508769 0.88143957]]


#numpy 본격적으로

In [ ]:
import numpy as np
a=np.array([1,'2',3,4])
print(a)
print(a.dtype) #data type
print(a.shape) #(갯수, )

['1' '2' '3' '4']
<U21
(4,)


In [ ]:
A=np.array([[1,2],[3,4]]) #이 셀부터는 import numpy as np는 실행 했다 치고 작성
# A=np.array([1,2],[3,4,5]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함

print(A)
print(A.shape)
print(A.ndim) #대괄호 갯수, 차원의 수
print(A.size) #전체 성분의

[[1 2]
 [3 4]]
(2, 2)
2
4


In [ ]:
print(np.zeros(5))
print(np.zeros_like(A))
print(np.zeros((3,3))) # 튜플을 입력으로! 그냥 np.zeros(3,3)은 안돼요
print(type(np.arange(3,10,2))) # range랑 같은데 array로 만들어줌
print(np.arange(0,1,0.1)) #소수점 가능
print(np.linspace(0,1,10, endpoint=False)) #0에서부터 1포함(default) 10개

[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
a= np.array([1,2,3])
b= np.array([4,5,6])
c= a+b
d= a-b
print(c)
print(d)  # list와 np.array가 다른 점이 이것

print(a*b) # 곱셈은? 성분끼리의 곱! (Hadamard product)
print(a/b) # 나누기도 마찬가지, 제곱도 됨

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])

print(A@B) # 행렬의 곱

[[ 7 10]
 [15 22]]


##numpy 의 인덱싱과 슬라이싱

In [ ]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(A[0][2])
print(A[0,2])
print(A[1,:]) #1행, 전부
print(A[1,0:3:2])
print(A[:,2]) #전부,2열

3
3
[4 5 6]
[4 6]
[3 6 9]


In [ ]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) #false

A=np.array([[1,2,3,4],[5,3,7,3]])
print(A==3)

A[A==3] = 100
print(A)

A=np.array([[1,2],[3,4],[5,6],[7,8]])
B=np.array([True,False,False,True]) #참고로 그냥 리스트여도 됨

A[B,:] # 0 행행, 3행행 슬라이싱

b=np.array([1,2,3,4])
print(b)
print(b[[True,True,False,False]]) #numpy에서만 이런 인덱싱이됨

False
[[False False  True False]
 [False  True False  True]]
[[  1   2 100   4]
 [  5 100   7 100]]
[1 2 3 4]
[1 2]
